version: "3.3"

services:
  app:
    build:
      context: ./docker/nodejs
      dockerfile: Dockerfile
      args:
        NODE_ENV: "${NODE_ENV}"
        DOCKER_UID: "${DOCKER_UID}"
        DOCKER_GID: "${DOCKER_GID}"
        DOCKER_USER: "${DOCKER_USER}"
        DOCKER_GROUP: "${DOCKER_GROUP}"
        DB_CONNECTION: "${DB_CONNECTION}"
        DB_DATABASE: "${DB_DATABASE}"
        DB_USERNAME: "${DB_USERNAME}"
        DB_PASSWORD: "${DB_PASSWORD}"
        DB_HOST: "${DB_HOST}"
        DB_PORT: "${DB_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:${FORWARD_APP_PORT:-8080}:8080"
    volumes:
      - "./:/home/${DOCKER_USER}/app"
    networks:
      - app
    restart: always
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "127.0.0.1:${FORWARD_MONGO_PORT:-27017}:27017"
    volumes:
      - "app-mongo:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "127.0.0.1:${FORWARD_MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DB_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_PASSWORD}"
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/

  meilisearch:
    image: "getmeili/meilisearch:v1.2.0"
    ports:
      - "127.0.0.1:${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    volumes:
      # - 'app-meilisearch:/meili_data'
      - "./docker/volumes/meilisearch:/meili_data"
    networks:
      - app
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--spider",
          "http://localhost:7700/health",
        ]
      retries: 3
      timeout: 5s

  redis:
    image: "redis:alpine"
    ports:
      - "127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "app-redis:/data"
    networks:
      - app
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

networks:
  app:
    driver: bridge
    enable_ipv6: false

volumes:
  app-mongo:
    driver: local
  app-redis:
    driver: local
  app-meilisearch:
    driver: local
